import { mkdir, readFile, writeFile } from "node:fs/promises";
import { watch, type FSWatcher } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

type ProjectConfig = {
  deckAppManifest: string;
};

type DeckAppManifest = {
  name: string;
  entry: string;
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const jsRoot = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(jsRoot, "..");
const configPath = path.join(jsRoot, "vitadeck.config.json");
const generatedDir = path.join(jsRoot, "src", "generated");
const generatedPath = path.join(generatedDir, "active-deck-app.ts");

async function readJson(filePath: string): Promise<unknown> {
  try {
    return JSON.parse(await readFile(filePath, "utf8"));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Could not read ${path.relative(repoRoot, filePath)}: ${message}`, { cause: error });
  }
}

function assertObject(value: unknown, sourcePath: string): asserts value is Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${path.relative(repoRoot, sourcePath)} must contain a JSON object.`);
  }
}

function requireString(value: unknown, name: string, sourcePath: string): string {
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`${path.relative(repoRoot, sourcePath)} must define a non-empty "${name}" string.`);
  }
  return value;
}

async function readProjectConfig(): Promise<ProjectConfig> {
  const config = await readJson(configPath);
  assertObject(config, configPath);
  return {
    deckAppManifest: requireString(config.deckAppManifest, "deckAppManifest", configPath),
  };
}

async function readDeckAppManifest(manifestPath: string): Promise<DeckAppManifest> {
  const manifest = await readJson(manifestPath);
  assertObject(manifest, manifestPath);
  return {
    name: requireString(manifest.name, "name", manifestPath),
    entry: requireString(manifest.entry, "entry", manifestPath),
  };
}

function assertInsideRepo(filePath: string, message: string): void {
  if (filePath !== repoRoot && !filePath.startsWith(repoRoot + path.sep)) {
    throw new Error(message);
  }
}

function toImportPath(fromFile: string, toFile: string): string {
  let relativePath = path.relative(path.dirname(fromFile), toFile).replaceAll(path.sep, "/");
  if (!relativePath.startsWith(".")) relativePath = `./${relativePath}`;
  return relativePath.replace(/\.(tsx|ts|jsx|js)$/, "");
}

async function regenerate(): Promise<void> {
  const config = await readProjectConfig();
  const manifestPath = path.resolve(jsRoot, config.deckAppManifest);
  assertInsideRepo(manifestPath, "deckAppManifest must point inside the VitaDeck repository.");

  const manifest = await readDeckAppManifest(manifestPath);
  const entryPath = path.resolve(path.dirname(manifestPath), manifest.entry);
  assertInsideRepo(
    entryPath,
    `${path.relative(repoRoot, manifestPath)} entry must point inside the VitaDeck repository.`,
  );

  const entryImportPath = toImportPath(generatedPath, entryPath);
  const source = `// Generated by js/scripts/generate-active-deck-app.ts
// Active Deck App: ${manifest.name}
export { default } from "${entryImportPath}";
`;

  await mkdir(generatedDir, { recursive: true });
  await writeFile(generatedPath, source);

  console.log(`Generated ${path.relative(repoRoot, generatedPath)} from ${path.relative(repoRoot, manifestPath)}`);
}

const watchMode = process.argv.includes("--watch");

if (!watchMode) {
  await regenerate();
} else {
  let manifestWatcher: FSWatcher | undefined;
  let debounceTimer: ReturnType<typeof setTimeout> | undefined;

  const runDebounced = (): void => {
    if (debounceTimer !== undefined) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(async () => {
      debounceTimer = undefined;
      try {
        await regenerate();
      } catch (error) {
        console.error(error);
      }
      try {
        await bindManifestWatcher();
      } catch {
        /* config may be invalid until user fixes it */
      }
    }, 50);
  };

  async function bindManifestWatcher(): Promise<void> {
    manifestWatcher?.close();
    manifestWatcher = undefined;
    const cfg = await readProjectConfig();
    const manifestPath = path.resolve(jsRoot, cfg.deckAppManifest);
    manifestWatcher = watch(manifestPath, runDebounced);
  }

  await regenerate();
  await bindManifestWatcher();
  watch(configPath, runDebounced);

  await new Promise<void>(() => {
    /* until SIGINT / SIGTERM */
  });
}
